### ISSUE TITLE
highpixel font rendering displays filled-in glyphs

### ISSUE THREAD

**Issue by tcsavage** [uopcs/warrior#12]
Some glyphs (namely upper and lower case O and 8) are filled in when rendered on Mac OS X (see attached screenshots).

This appears to be an issue with font rendering in OS X itself rather than any of the browsers (see screenshot of TTF font rendered in OS X font viewer). Regardless, the following browsers have been tested:
* Chrome OS X (29.0.1547.65) - broken
* Firefox OS X (23.0.1) - broken
* Safari OS X (6.0.5 (8536.30.1)) - broken
* Firefox Linux (21.0) - **works**

**Screenshots**

![screen shot 2013-09-09 at 01 20 10](https://f.cloud.github.com/assets/134930/1104147/a263a19c-18e6-11e3-84a1-0127d4ce4eff.png)

![screen shot 2013-09-09 at 01 26 39](https://f.cloud.github.com/assets/134930/1104148/b8ba175a-18e6-11e3-9402-8c7edcc52cc2.png)

**Comment by zoetrope69** [comment]
Changed the font so no longer relevant
